version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - data-postgresql-challenge-api-fr:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge-api-db
  app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - ./list.env
    depends_on:
      - db
volumes:
  data-postgresql-challenge-api-fr: